### ISSUE TITLE
Missing freebsd box

### ISSUE THREAD

**Issue by gasperz** [wunki/vagrant-freebsd#13]
From vagrant file: http://files.wunki.org/freebsd-10.1-amd64-wunki.box
This link is dead.

**Comment by theodorosploumis** [comment]
Any news for this?

**Comment by krzysztofantczak** [comment]
+1

**Comment by wunki** [comment]
Sorry guys, little time and having trouble to configure the new `httpd` server on OpenBSD.

**Comment by andoriyu** [comment]
Can you upload box to Vagrant cloud please?

**Comment by bval** [comment]
:+1: for uploading to Atlas/Vagrantcloud. No need to run your own `httpd` for this.

**Comment by andoriyu** [comment]
@bval https://atlas.hashicorp.com/infinitycode/boxes/freebsd-10.1-zfs-pure slightly different build, but the same thing. Requires the same Vagrantfile as box in this repo.

**Comment by bval** [comment]
@andoriyu thanks! Here's hoping @wunki is able to publish some of his own.

**Comment by brd** [comment]
Thanks to help from the FreeBSD Release Engineering team I have been able to get Vagrant support added to the FreeBSD Release Builds. Currently this is only supporting VMWare, but I should have VirtualBox support committed in the next day or so.

You can find the prereleases available from the Atlas site here: https://atlas.hashicorp.com/FreeBSD/

FreeBSD 10.2 will be the first official release with Vagrant images, but it is not due till August: https://www.freebsd.org/releases/10.2R/schedule.html

**Comment by emve-dev** [comment]
@brd great news!

**Comment by brd** [comment]
I just wanted to leave a note that the VirtualBox support took a bit longer, but is now in. So the next scheduled builds for 10.2, will include VirtualBox images. Which will be BETA3 or RC1, see the schedule for more info: https://www.freebsd.org/releases/10.2R/schedule.html

**Comment by andygrunwald** [comment]
@brd FreeBSD 10.2 is out afaik (https://www.freebsd.org/releases/10.2R/announce.html).
Does this Vagrant file here special configs or is there a need to change something?
Or is there already some vagrant out of the box use images?

THX to keep us posted.

**Comment by brd** [comment]
Hi @andygrunwald. Yeah check out this article I wrote:

http://blogs.freebsdish.org/brd/2015/08/07/official-vagrant-freebsd-images/

**Comment by wunki** [comment]
Finally got the time to update everything. You can find all the changes in the new Vagrantfile.
