### ISSUE TITLE
Box file missing again

### ISSUE THREAD

**Issue by jesteves** [wunki/vagrant-freebsd#18]
Hello @wunki .  I'm afraid the box is missing again (ref: #13), but for another reason:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[...]
==> default: Adding box 'freebsd-10.2-amd64-wunki' (v0) for provider: virtualbox
    default: Downloading: https://wunki.org/files/freebsd-10.2-amd64-wunki.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL: no alternative certificate subject name matches target host name 'wunki.org'
```

Your [Vagrantfile points to winki.org](https://github.com/wunki/vagrant-freebsd/blob/master/Vagrantfile#L14) but it seems that certificate at winki.org is actually assigned to bitsonpaper.org..

Are you still maintaining this box image?

**Comment by sputnick-dev** [comment]
```
$ curl -LI "https://wunki.org/files/freebsd-10.2-amd64-wunki.box"
HTTP/2 404
```

Seems an abandoned project, better goes to official image : https://forums.freebsd.org/threads/official-vagrant-freebsd-images.52717/

**Comment by jesteves** [comment]
@sputnick-dev Yup..  It totally looks like that...

Anyway, I'm closing this request since I'm not longer interested (still using FreeBSD on Virtualbox, but no longer using Vagrant...).
